spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  type-aliases-package: "ru.reimu.demo.reactor.more.dto"